### PR TITLE
CI runs lint

### PR DESCRIPTION
**Pull request by richytong**
Allows us to enforce lint.

### CODE REVIEW

**Comment by jremi** [comment]
Thanks for updating the ci workflow …

please check failed test … assert failed. 🙏

**Comment by richytong** [comment]
Probably a race condition, CI should just be rerun

**Comment by jremi** [comment]
Re-ran CI for both the failed job and also all jobs. Same issue. 👀

**Comment by richytong** [comment]
Fixed CI

**Comment by jremi** [comment]
Thank you 🙏

**Pull request merged**
