### PR TITLE
remove unnecessary this.websocket

### PR DESCRIPTION
**Pull request by richytong**
`this.websocket` was only being used to store the reference for `wstream`, so I removed it and stored `wstream` on `this` directly. This also means users of the library will not have to take the extra step of calling `setWebsocket` so it will make the library easier to use.

### CODE REVIEW

**Review by jremi — CHANGES_REQUESTED** [review]
Please remove dangling comma on line 91

**Comment by richytong** [comment]
Removed

**Comment by jremi** [comment]
@richytong please resolve conflict … remove unused variables from test … I already removed on eslint tooling branch that just got merged

**Comment by richytong** [comment]
Resolved

**Pull request merged**
